<a href="https://colab.research.google.com/github/AureohDev/Tech_Lead_Exos/blob/main/Algo/Exos/NumpyExo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercices pratiques
Ce notebook à pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste de questions à faire ! Il ne faut pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/). 

#### Q1 : Importer le package numpy 

In [ ]:
import numpy as np

#### Q2 : Afficher la version de numpy et la configuration 

In [ ]:
np.version.version

'1.18.5'

#### Q3 : Créer un vecteur nul de taille 10

In [ ]:

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 4ème place (index 4) du vecteur

In [ ]:
vecteur = np.zeros(10)
vecteur[4] = 1
print(vecteur)

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 

In [ ]:
z = np.arange(10,51)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [ ]:
np.flip(z)

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10])

#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 

In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Q8 : Créer une matrice identié 3x3 

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Q9 : Créer une matrice 3x3x3 avec des valeurs random 

In [ ]:
np.random.rand(3,3,3)

array([[[0.59138765, 0.46129841, 0.13418757],
        [0.84455498, 0.37601916, 0.83043261],
        [0.58979856, 0.77107387, 0.80081792]],

       [[0.4835318 , 0.97868575, 0.92722321],
        [0.1759344 , 0.69962934, 0.11995874],
        [0.33960515, 0.13805484, 0.94583186]],

       [[0.07140042, 0.17742296, 0.52259635],
        [0.97959239, 0.13630952, 0.96925233],
        [0.21557405, 0.23154138, 0.86620416]]])

#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [ ]:
matrice = np.random.rand(10,10)
matrice.min(), matrice.max()

(0.008437021710715142, 0.9919675595526289)

#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale 

In [ ]:
np.diag(np.array([1,2,3,4]),-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  

In [ ]:
a = np.random.randint(1, 10, 5)
print(a)
np.sum(a)

[9 7 1 6 5]


28

#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

In [ ]:
b = np.random.randint(1, 10, 5)
print(b)
np.mean(b)

[6 7 5 5 1]


4.8

#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :
```python 
l = [x for x in range(11)]
```

In [ ]:
l = [x for x in range(11)]
print(l)
np.size(l)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


11

#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS 

In [ ]:
 #np.random.uniform(0, 1, 10)
 np.linspace(0,1,11,False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

In [ ]:
A = np.random.randint(1, 3, 5)
B = np.random.randint(1, 3, 5)
print(A)
print(B)

comparison = A == B
is_equal = comparison.all()
print(is_equal)

[2 1 1 1 1]
[2 1 2 1 1]
False


#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

In [ ]:
float_array = np.arange(2,10,dtype=float)
print(float_array)
int_array = float_array.astype(int)
print(int_array)

[2. 3. 4. 5. 6. 7. 8. 9.]
[2 3 4 5 6 7 8 9]


#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type 

In [ ]:
Z = np.random.random((5,5))
print(Z)
Z =(Z- np.mean (Z)) / (np.std (Z))
print(Z)


[[0.11546797 0.05843029 0.23266309 0.68355095 0.20520687]
 [0.7173762  0.20698049 0.5715185  0.36002915 0.72245423]
 [0.9306737  0.34924704 0.13966214 0.75740282 0.01823792]
 [0.898559   0.32744308 0.59158108 0.23695869 0.57852299]
 [0.10921651 0.10922443 0.37837093 0.33238494 0.03590529]]
[[-0.98544588 -1.19268957 -0.55962302  1.07865647 -0.65938386]
 [ 1.2015589  -0.65293952  0.67159193 -0.09684452  1.2200097 ]
 [ 1.97656518 -0.13602078 -0.8975375   1.3469937  -1.3387266 ]
 [ 1.85987794 -0.21524444  0.74448837 -0.54401516  0.69704241]
 [-1.00816025 -1.00813148 -0.03020053 -0.19728842 -1.27453306]]


#### Q19 : Créer une matrice random `M` 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 

In [ ]:
M = np.random.randint(1,10,4).reshape(2,2)
print(M)
print(M.transpose())

[[3 6]
 [5 9]]
[[3 5]
 [6 9]]


#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

In [ ]:
N = int(input('Valeur de N :'))
M2 = np.random.rand(N,N)
print(M2)

M2[np.random.randint(0,N-1),np.random.randint(0,N-1)] = 7
print(M2)


Valeur de N :2
[[0.4220162  0.12302493]
 [0.06891063 0.41283944]]
[[7.         0.12302493]
 [0.06891063 0.41283944]]


#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]
